### ISSUE TITLE
Failed to upload file to Object Storage.

### ISSUE THREAD

**Issue by JoshBoluga** [watson-developer-cloud/visual-recognition-coreml#18] opened 2018-04-09 13:30 UTC
I'm still getting [this issue](https://github.com/watson-developer-cloud/visual-recognition-coreml/issues/11) 99% of the time.

I would have re-opened the issue but I don't appear to have the ability to.

**Comment by germanattanasio** [comment] 2018-04-09 19:10
Please provide a set of reproducible steps. 
Check the CONTRIBUTING.md for an example.

**Comment by JoshBoluga** [comment] 2018-04-10 08:09
- Login to dataplatform.ibm.com
- Select my project
- Select the load tab on the right pane
- Drag a file into the pane or click browse and choose a file

The upload will start as normal. Progress meter will proceed but occasionally will jump back to the beginning. After it jumps back to the beginning a few times, it will stop and present the error "Failed to upload file to Object Storage."

As I mentioned in #11, I'm not sure if I'm in the right place for this issue. If I'm not, a) sorry and b) where should I be?

**Comment by JoshBoluga** [comment] 2018-04-30 13:29
This issue still persists. Is there any update on this or where I should be asking about this? Many thanks.

**Comment by JoshBoluga** [comment] 2018-04-30 14:36
Thanks. I opened one: Ticket number: CS0031486

**Comment by JohnnyKam** [comment] 2018-05-01 15:46
Can you invite me into your project? My email is kjohnny@ca.ibm.com

**Comment by JoshBoluga** [comment] 2018-05-01 15:52
@JohnnyKam I tried but got this message "You cannot add kjohnny@ca.ibm.com to this restricted project. You can only add a member of your company (if your company has federated SAML with IBM Cloud) or a member of the project creator's IBM Cloud account.
To add members of the project creator's IBM Cloud account, you must be a member of that account."

I can barely parse that.

**Comment by JohnnyKam** [comment] 2018-05-01 17:41
In the header can you click on manage > account > users. 

![image](https://user-images.githubusercontent.com/7724152/39484864-0b3f04bc-4d45-11e8-8bab-0ea4ab17fc88.png)

This will take you into IBM cloud, where you can invite me into your account. Once I'm in the account you should be able to add me as a collaborator in your project.

**Comment by JoshBoluga** [comment] 2018-05-02 08:09
Okay, you're invited to the account. I'll add you as a collaborator once you're in. Thanks.

**Comment by JohnnyKam** [comment] 2018-05-02 14:16
@JoshBoluga Please add me as a collaborator

**Comment by JohnnyKam** [comment] 2018-05-02 14:25
What browser and OS are you using? I was able to upload the files into object storage without any issues

**Comment by JoshBoluga** [comment] 2018-05-02 14:34
I'm using macOS High Sierra 10.13.4 and Safari 11.1. I've also tried Chrome which produced the same behaviour.

**Comment by JohnnyKam** [comment] 2018-05-02 15:30
I can't seem to reproduce it in Safari 11 or Chrome 66 or Firefox

**Comment by germanattanasio** [comment] 2018-05-02 17:31
it seems like it's working for you now @JoshBoluga so I'm going to close this issue.

Feel free to reopen it if you face this problem again.

**Closed by germanattanasio** 2018-05-02 17:31 UTC
Labels: bug

**Comment by lbiazoto** [comment] 2018-07-05 17:43
Hi, how did you manage to fix it? I am getting the same error 100% of the time
"Failed to upload file to Object Storage."

**Comment by nadamakram** [comment] 2018-09-18 11:29
I am having the same problem and I don't know what to do

**Comment by bourdakos1** [comment] 2018-09-18 12:42
@JoshBoluga @nadamakram how large are the files you are trying to upload?

**Comment by nadamakram** [comment] 2018-09-18 13:36
It's 5.60 MB
If it's big for Watson studio, Is there another way to upload?

**Comment by ronanb3** [comment] 2019-09-18 20:03
I have the exact same issue on MacOS too ... Is there any solution ?

**Comment by nadamakram** [comment] 2019-09-18 21:30
I discovered that the problem is my subscription is limited so I can't use
that big size.

**Comment by SatyaMeghana** [comment] 2020-06-04 04:03
I do have the same problem is there any solution .....my csv file is about 14 MB.

**Comment by BNMEZR** [comment] 2020-06-09 10:07
i have the same prolem and my (Zip file) is just 85 Mo ,and our internet upload is good........any solutions?

**Comment by MrAjakkala** [comment] 2020-06-26 09:18
I have the same problem and my (Zip file) is just 25 MB ,and our internet upload is good.
